### PR TITLE
fix: Operands no longer classified as remarks when instruction or macro is not recognized

### PR DESCRIPTION
**Pull request by jirimosinger**

### CODE REVIEW

**Review by slavek-kucera — COMMENTED** [review]
This will definitely require additional tests with some invalid text as operands (unbalanced parenthesis, quotes, ampersand without variable name etc.). Only the E049 should be generated.

**Comment by jirimosinger** [comment]
It looks like this now:

image

**Review by slavek-kucera — APPROVED** [review]
👍

**Comment by slavek-kucera** [comment]
Maybe one more thing to verify, does it behave the same way (diagnostic-wise) when the statements are brought in via copybook?

**Comment by jirimosinger** [comment]
Yup, it shows only E049 and highlighting stays the same
image

**Comment by jirimosinger** [comment]
@VitGottwald: Is this something you've had in mind for this [story](https://rally1.rallydev.com/#/289622436736d/teamboard?detail=%2Fuserstory%2F686623400283&fdp=true) (see screenshots above)?

**Comment by slavek-kucera** [comment]
I think the story is about something slightly different, but this PR should go in regardless. So feel free to merge if you are done.

**Comment by VitGottwald** [comment]
Thank you @jirimosinger it achieves exactly what I was looking for.

The only diference is that the implementation is in language server. I was curious to find out if we could tweak the [textmate grammar](https://github.com/BroadcomMFD-DevOps/che-che4z-lsp-for-hlasm/blob/development/clients/vscode-hlasmplugin/syntaxes/hlasm.tmLanguage.json) to handle line continuations. Then the first colouring by VS Code would get it "right" as well.

**Pull request merged**
